export const FETCH_USERS = "FETCH_USERS";
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const FETCH_USER_TODOS = "FETCH_USER_TODOS";
export const GET_USER_TODOS_REQUEST = "GET_USER_TODOS_REQUEST";
export const GET_USER_TODOS_SUCCESS = "GET_USER_TODOS_SUCCESS";
export const GET_USER_TODOS_FAILURE = "GET_USER_TODOS_FAILURE";
